version: 2

updates:
- package-ecosystem: docker
  directory: "/docker"
  schedule:
    interval: daily
    time: '04:00'
    timezone: Europe/Berlin
  assignees:
  - fefas

- package-ecosystem: composer
  directory: "/docker"
  schedule:
    interval: daily
    time: '04:00'
    timezone: Europe/Berlin
  assignees:
  - fefas
  versioning-strategy: increase
