name: Bauhaus PHP Package CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: bauhausphp/contributor-tool

    - name: Setup
      run: make setup pkg=middleware-chain
