deptrac:
  ignore_uncovered_internal_classes: true # ignore dependency to internal php classes

  paths:
  - ../packages
  - ../tests
  - ../vendor
  exclude_files: ~

  ruleset:
    ServiceResolver: [ Psr11 ]
    TestServiceResolver: [ +ServiceResolver, PhpUnit ]

  layers:
  - name: ServiceResolver
    collectors:
    - { type: directory, value: ../packages/service-resolver/public/ }
    - { type: directory, value: ../packages/service-resolver/private/, private: true }

  - name: TestServiceResolver
    collectors:
    - { type: class, value: Bauhaus\\Tests\\ServiceResolver\\GetTest }
    - { type: directory, value: ../tests/ServiceResolver/Doubles/ }

  - name: Psr11
    collectors: [ { type: directory, value: ../vendor/psr/container/ } ]

  - name: PhpUnit
    collectors: [ { type: directory, value: ../vendor/phpunit/ } ]

#  formatters:
#    graphviz:
#      groups:
#        Packages:
#        - ServiceResolver
#        Tests:
#        - TestServiceResolver
#        PSRs:
#        - PSR11
