name: CI
on: push

jobs:
  test-cs:
    name: Test CS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make build
    - run: make test level=cs

  test-unit:
    name: Test Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - run: make test level=unit
