name: CI
on: push

jobs:
  tests:
    name: Test packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
        #- cli
        #- message-handler
        - service-resolver
    steps:
    - uses: actions/checkout@v2
    - run: make -C docker build
    - run: |
        make setup package=${{ matrix.package }}
        make tests package=${{ matrix.package }}
        make coverage package=${{ matrix.package }} dryrun=y

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - run: make -C docker login username=${{ github.actor }} password=${{ secrets.GITHUB_TOKEN }}
    - run: make -C docker build
    - run: make -C docker push
