name: CI
on: push

jobs:
  test-cs:
    name: CS Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make build
    - run: make test level=cs

  test-unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - run: make test level=unit

  test-mutation:
    name: Mutation Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - run: make test level=mutation
