name: CI

on: push
concurrency: action-on-${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make build php=${{ matrix.php }}
    strategy:
      matrix:
        php: [ 8.2.0 ]

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - run: make test php=${{ matrix.php }} revision=${{ env.revision }}
    strategy:
      matrix:
        php: [ 8.2.0 ]
        level: [ unit, mutation ]
        #level: [ cs, unit, mutation ]

#  publish:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up deploy key
#        uses: webfactory/ssh-agent@v0.5.4
#        with:
#          ssh-private-key: ${{ secrets.PACKAGE_DEPLOY_KEY }}
#      - name: Set up git author
#        run: |
#          git config --global user.name "${{ github.event.commits[0].author.name }}"
#          git config --global user.email ${{ github.event.commits[0].author.email }}
#      - run: make publish package=${{ matrix.package }} branch=${{ github.ref_name }} revision=${{ env.revision }}
#    strategy:
#      matrix:
#        package: [ service-resolver ]
#
#  pr-control:
#    runs-on: ubuntu-latest
#    needs: [ build, test, publish ]
#    steps:
#      - name: You shall pass!
#        run: echo You shall pass!
