name: Docker
on: push

jobs:
  build:
    name: Build release condidate image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker
    outputs:
      compare: ${{ steps.compare.outputs.test }}
    steps:
    - uses: actions/checkout@v2
    - run: make pull tag=latest
    - run: make build tag=RC
    - id: compare
      run: echo "::set-output name=test::$(make compare tag1=RC tag2=latest)"
    - run: make save tag=RC output=release-candidate-image.tar
    - uses: actions/upload-artifact@v2
      with:
       name: release-candidate-image
       path: release-candidate-image.tar

  tests:
    name: Test published packages
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.compare == 'not equal' }}
    steps:
    - uses: actions/checkout@v2
    - run: make -C docker build tag=RC
    - run: |
        for p in $(cat ./published-packages.txt); do
          make setup package=$p
          make tests tag=RC package=$p
        done

  #publish:
  #  name: Publish new docker image
  #  runs-on: ubuntu-latest
  #  #if: ${{ github.ref == 'refs/heads/main' }}
  #  needs:
  #  - tests
  #  steps:
  #  - name: Checkout
  #    uses: actions/checkout@v2
  #  - name: Build
  #    run: make -C docker build
  #  - name: Login
  #    run: make -C docker login username=fefas password=${{ secrets.GHRC_TOKEN }}
  #  #- name: Push
  #  #  run: make -C docker push
