name: Docker Publish

on: pull_request

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build -t bauhausphp/dev:latest ./docker

    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish
      run: docker push bauhausphp/dev:latest
