name: Docker
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make -C docker build tag=RC
    - name: Test all packages
      run: |
        PACKAGES=$(cat ./published-packages.txt)
        for p in $PACKAGES; do
          make setup package=$p
          make tests tag=RC package=$p
        done
