name: CI

on: push
concurrency: action-on-${{ github.ref_name }}

env:
  version: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make build php=${{ matrix.php }} version=${{ env.version }} user=${{ github.actor }} pass=${{ github.token }}
    strategy:
      matrix:
        php: [ 8.2.0RC1, 8.1.9 ]

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - run: make test php=${{ matrix.php }} version=${{ env.version }} level=${{ matrix.level }}
    strategy:
      matrix:
        php: [ 8.2.0RC1, 8.1.9 ]
        level: [ cs, unit, mutation ]

  publish:
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - uses: actions/checkout@v3
      - run: make publish package=${{ matrix.package }} version=${{ env.version }} author='${{ github.event.commits[0].author }}'
    strategy:
      matrix:
        package:
        - service-resolver
