name: CI
on: push

env:
  version: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make publish php=${{ matrix.php }} version=${{ env.version }} username=${{ github.actor }} password=${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        php: [ 8.2.0RC1, 8.1.9 ]

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - run: make test php=${{ matrix.php }} version=${{ env.version }} level=${{ matrix.level }}
    strategy:
      matrix:
        php: [ 8.2.0RC1, 8.1.9 ]
        level: [ cs, unit, mutation ]
