name: Tests
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make build tag=dev-${{ github.sha }}
    - run: make push  tag=dev-${{ github.sha }} username=${{ github.actor }} password=${{ secrets.GITHUB_TOKEN }}

  tests:
    name: CS Test
    runs-on: ubuntu-latest
    strategy: { matrix: { level: [ cs, unit, mutation ] } }
    needs: build
    steps:
    - uses: actions/checkout@v3
    - run: make test level=${{ matrix.level }} tag=dev-${{ github.sha }}
