name: CI

on: push
concurrency: action-on-${{ github.ref_name }}

env:
  version: ${{ github.ref_name }}
  revision: ${{ github.sha }}

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3
  #  - run: make build php=${{ matrix.php }} version=${{ env.version }} user=${{ github.actor }} pass=${{ github.token }}
  #  strategy:
  #    matrix:
  #      php: [ 8.2.0RC1, 8.1.9 ]

  #test:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #  - uses: actions/checkout@v3
  #  - run: make test php=${{ matrix.php }} version=${{ env.version }} level=${{ matrix.level }}
  #  strategy:
  #    matrix:
  #      php: [ 8.2.0RC1, 8.1.9 ]
  #      level: [ cs, unit, mutation ]

  publish:
    runs-on: ubuntu-latest
    #needs: test
    strategy:
      matrix:
        package: [ service-resolver ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PACKAGE_DEPLOY_KEY }}

      - name: Set up git author
        run: |
          git config --global user.name "${{ github.event.commits[0].author.name }}"
          git config --global user.email ${{ github.event.commits[0].author.email }}

      - name: Push code
        run: make publish package=${{ matrix.package }} version=${{ env.version }} revision=${{ env.revision }}
