name: CI

on: push
concurrency: action-on-${{ github.ref_name }}

env:
  version: ${{ github.sha }}

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v3
  #  - run: make build php=${{ matrix.php }} version=${{ env.version }} user=${{ github.actor }} pass=${{ github.token }}
  #  strategy:
  #    matrix:
  #      php: [ 8.2.0RC1, 8.1.9 ]

  #test:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #  - uses: actions/checkout@v3
  #  - run: make test php=${{ matrix.php }} version=${{ env.version }} level=${{ matrix.level }}
  #  strategy:
  #    matrix:
  #      php: [ 8.2.0RC1, 8.1.9 ]
  #      level: [ cs, unit, mutation ]

  publish:
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PACKAGE_DEPLOY_KEY }}
      - name: Set up git author
        uses: fregante/setup-git-user@v1
      - name: push code
        run: make publish package=${{ matrix.package }} version=${{ env.version }}
    strategy:
      matrix:
        package:
        - service-resolver
